### ISSUE TITLE
utf8 in the input window is odd

### ISSUE THREAD

**Issue by ashak** [c-hudson/muddler#3]
If I type unicode characters into the input window, they appear odd. In the output they appear fine. In this example the £ symbol is causing the problem, the input window shows the Â character before the £ character when I type the £ character on my keyboard. I get similar issues if I paste other unicode things, the output is obviously different, for some of the funky characters I don't even see the correct thing in my input, but it appears ok in the output, the flexed biceps unicode character is an example of that

![image](https://github.com/user-attachments/assets/524ceaad-4ca5-44f9-9b02-753d5689ef69)
![image](https://github.com/user-attachments/assets/424bd666-a226-47f9-9262-ca07708db71b)

If I backspace over one of the two characters it displays in the input, I then get odd stuff in my output. Using the above example, if I backspace over the £ character, but leave the Â that it puts into the input, then my output shows the ?. I guess this could be the talker i'm using trying to not blow up when dealing with the odd character or something?

![image](https://github.com/user-attachments/assets/766df7cb-649a-4576-a4d3-bced2f9c7df5)

I also see that Wide character message whenever I send any unicode characters

**Comment by c-hudson** [comment]
I've committed a change that I believe resolves this. It defaults the keyboard input handling to utf8 which may or may not be the correct answer. I.e. Not all worlds support utf8 and the encoding setting is set at the world level but the keyboard input pane is used by all worlds. The correct answer may be to store the original input before converting to utf8/fansi/etc and then reconvert it every time a world switch happens. This also seems less idea since it will impact cursor position as the string will have different lengths depending upon if the string is properly converted or not. If this doesn't fix the problem, please post and i'll take another look at it. FYI - Thanks for the bug reports!

**Comment by ashak** [comment]
This works much better, at least for me in a world that supports utf8

I do still get the 'Wide character printf at loggit_world line 15' message, it seems to be whenever a unicode character is displayed in the output.

**Comment by c-hudson** [comment]
I'm not able to reproduce this on my computer, so i wonder if the encoding is set incorrectly for the world (as far as printf is concerned) . What is the encoding set to for this world? I.e. what show for the encoding when you type /world?

**Comment by c-hudson** [comment]
Also, what OS is it running on?

**Comment by ashak** [comment]
If I type /world I get:
   Encoding     : [ UTF-8 ]

OS is kinda interesting although I don't expect any of it to really cause a problem, it never has with anything else
muddler itself is running within a container that make up one pod on a Kubernetes cluster
The container I build to include muddler is based on the official Debian stable container: debian:stable-slim
The slim means it's just stripped down to something quite minimal

**Comment by c-hudson** [comment]
I believe this is fixed. I should have paid more attention to the error provided as the answer was staring me right in my face.. I assumed the error was on the printing of characters to the console instead of on the writing to the log file (which i didn't have enabled). Writing to the world's logfile is now opened with the correct encoding. You'll still get errors if the encoding is set wrong (in /world) but I don't believe there is a way around that.

**Comment by ashak** [comment]
Yes, that has fixed it. Thanks
